//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by injection.rc
//
#define ID_DLG_TAB_MAIN                 99
#define ID_DLG_CHOOSESHOP               100
#define ID_DLG_LAYERS                   101
#define ID_ENCRYPTION                   102
#define ID_BT_FLUSH                     103
#define ID_CH_VERBOSE                   104
#define ID_BT_DUMP                      105
#define ID_EB_CREATENAME                106
#define ID_BT_CREATE                    107
#define ID_LB_SHOPLISTS                 108
#define ID_BT_EDITLIST                  109
#define ID_BT_SHOPLIST                  110
#define ID_BT_DELETELIST                111
#define ID_BT_SAVE                      112
#define ID_CH_FLUSH                     113
#define ID_BT_SHOP                      114
#define ID_ST_VERSION                   116
#define ID_CH_DMENUS                    117
#define ID_CH_FSND                      118
#define ID_CH_LIGHT                     119
#define ID_CH_FSPEECH                   120
#define ID_CH_VMENU                     121
#define ID_CH_UNDEAD                    122
#define ID_CH_TRACKER                   123
#define ID_CH_STLTHCNT                  124
#define ID_CH_CORPSOP                   125
#define ID_CH_SMOOTH                    126
#define ID_CH_SOCKSCAP                  127
#define ID_CH_HUNGMSG                   128
#define ID_CH_USEINJ                    129
#define ID_CH_SBAR                      130
#define ID_CH_POISON                    131
#define ID_CH_WORLD                     132
#define ID_DLG_EDITLIST                 200
#define ID_ST_LISTNAME                  202
#define ID_LB_SHOPLIST                  203
#define ID_LB_VENDORLIST                204
#define ID_BT_DONE                      205
#define ID_BT_DELETE                    206
#define ID_BT_ADDSOME                   207
#define ID_EB_QUANTITY                  209
#define ID_EB_ADDNAME                   211
#define ID_BT_ADDNAME                   213
#define ID_DLG_BUYSELL                  300
#define ID_EB_NPCNAME                   302
#define ID_BT_BUY                       303
#define ID_BT_SELL                      304
#define ID_LB_RESULTS                   306
#define ID_BT_DONEBUY                   307
#define ID_BT_CANCEL                    308
#define ID_ST_STATUS                    310
#define ID_DLG_MAIN                     400
#define ID_TC_MAINTABS                  401
#define ID_DLG_TAB_WEAPONS              500
#define ID_BT_ARM                       502
#define ID_BT_DISARM                    503
#define ID_BT_SETARM                    504
#define ID_DLG_TAB_CLOTHING             600
#define ID_LB_DRESS                     601
#define ID_BT_DRESS                     602
#define ID_BT_UNSETDRESS                603
#define ID_BT_SETDRESS                  604
#define ID_EB_DRESSNAME                 606
#define ID_BT_ADDDRESS                  607
#define ID_DLG_TAB_USE                  700
#define ID_LB_USE                       701
#define ID_EB_GRAPHIC                   703
#define ID_EB_USENAME                   705
#define ID_BT_NEWUSE                    706
#define ID_BT_SAVEUSE                   707
#define ID_BT_USE                       708
#define ID_EB_GRAPHIC2                  708
#define ID_BT_TARGET                    709
#define ID_BT_DELETEUSE                 710
#define ID_DLG_TAB_DISPLAY              800
#define ID_CH_DISPLAY_HP                801
#define ID_CH_DISPLAY_MANA              802
#define ID_CH_DISPLAY_STAMINA           803
#define ID_CH_DISPLAY_ARMOR             804
#define ID_CH_DISPLAY_WEIGHT            805
#define ID_CH_DISPLAY_GOLD              806
#define ID_CH_DISPLAY_B                 807
#define ID_CH_DISPLAY_BM                808
#define ID_CH_DISPLAY_BP                809
#define ID_CH_DISPLAY_GA                810
#define ID_CH_DISPLAY_GS                811
#define ID_CH_DISPLAY_MR                812
#define ID_CH_DISPLAY_NS                813
#define ID_CH_DISPLAY_SA                814
#define ID_CH_DISPLAY_SS                815
#define ID_CH_DISPLAY_VA                816
#define ID_CH_DISPLAY_EN                817
#define ID_CH_DISPLAY_WH                818
#define ID_CH_DISPLAY_FD                819
#define ID_CH_DISPLAY_BR                820
#define ID_CH_DISPLAY_AR                821
#define ID_CH_DISPLAY_H                 822
#define ID_CH_DISPLAY_C                 823
#define ID_CH_DISPLAY_M                 824
#define ID_CH_DISPLAY_L                 825
#define ID_CH_DISPLAY_BT                826
#define ID_CH_DISPLAY_FIX               827
#define ID_DLG_TAB_OBJECT               900
#define ID_LB_OBJECT                    901
#define ID_EB_SERIAL                    903
#define ID_EB_OBJNAME                   905
#define ID_BT_NEWOBJ                    906
#define ID_BT_SAVEOBJ                   907
#define ID_BT_OBJECT                    908
#define ID_EB_SERIAL2                   908
#define ID_BT_TARGETOBJ                 909
#define ID_BT_DELETEOBJ                 910
#define ID_BT_LAYERSOBJ                 911
#define ID_BT_OBJUSE                    913
#define ID_BT_OBJSRC                    914
#define ID_BT_OBJCB                     915
#define ID_BT_OBJUNS                    916
#define ID_BT_OBJWAIT                   917
#define ID_BT_OBJTARG                   918
#define ID_BT_OBJCLICK                  919
#define ID_DLG_TAB_HOTKEY               1000
#define ID_LB_HOTKEY                    1001
#define ID_EB_COMMAND                   1003
#define ID_SKILLS                       1003
#define ID_WEBSITE                      1004
#define ID_EB_HOTKEY                    1005
#define ID_ED_SKILLCAP                  1005
#define ID_WEBSITE2                     1005
#define ID_BT_NEWHOTKEY                 1006
#define ID_ED_STATCAP                   1006
#define ID_WEBSITE3                     1006
#define ID_BT_SAVEHOTKEY                1007
#define ID_BT_SAVESKILLS                1007
#define ID_BT_DELETEHOTKEY              1008
#define ID_BT_SKILLSRESET               1008
#define ID_SKILLREAL                    1009
#define ID_EB_HOTKEY_TEXT               1010
#define ID_EB_OBJDESC                   1010
#define ID_ED_XY                        1011
#define ID_EB_OBJINFO                   1011
#define ID_LOL                          1012
#define ID_BLOL                         1013
#define IDR_S1                          1014
#define IDR_S2                          1015
#define ID_TARGXYZ                      1015
#define IDR_S3                          1016
#define IDR_S4                          1017
#define ID_ED_FCOLOR                    1017
#define IDC_FONT                        1020
#define ID_BT_DYE                       1021
#define IDC_UNSET                       1022
#define ID_DLG_TAB_EXTERNAL             1100
#define ID_DLG_TAB_SKILLS               1200
#define ID_LI_SKILLS                    1201
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
